level: info

redis:
  username: ""
  password: ""
  addresses:
    - ""
  database: 0
  sentinel: false

api:
  enabled: true
  bind: :3000

monitoring:
  enabled: true
  bind: :9100
  labels:
    - key: key
      value: value

health:
  enabled: true
  bind: :9101

pod:
  name: ""
