apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventapi
  namespace: app
spec:
  selector:
    matchLabels:
      app: eventapi
  template:
    metadata:
      labels:
        app: eventapi
    spec:
      volumes:
        - name: config
          configMap:
            name: eventapi-config
            defaultMode: 420
      containers:
        - name: eventapi
          image: ${IMAGE}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: metrics
              containerPort: 9100
              protocol: TCP
            - name: health
              containerPort: 9200
              protocol: TCP
          envFrom:
            - secretRef:
                name: eventapi-secret
          env:
            - name: API_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: API_K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: "2"
              memory: 3Gi
            requests:
              cpu: 300m
              memory: 2Gi
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
          livenessProbe:
            tcpSocket:
              port: health
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: health
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: eventapi
  namespace: app
  labels:
    app: eventapi
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: metrics
    - name: health
      protocol: TCP
      port: 9200
      targetPort: health
  selector:
    app: eventapi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eventapi-config
  namespace: app
data:
  config.yaml: |
    level: info

    api:
      enabled: true
      bind: 0.0.0.0:3000
      heartbeat_interval: 25000
      subscription_limit: 100

    health:
      enabled: true
      bind: 0.0.0.0:9200

    monitoring:
      enabled: true
      bind: 0.0.0.0:9100

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventapi
  namespace: app
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/hostname: events.7tv.io
spec:
  ingressClassName: cloudflared
  tls:
    - hosts:
        - events.7tv.io
      secretName: 7tv-io-tls
  rules:
    - host: events.7tv.io
      http:
        paths:
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: eventapi
                port:
                  name: health
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eventapi
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventapi-old
  namespace: app
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    external-dns.alpha.kubernetes.io/hostname: events.7tv.app
spec:
  ingressClassName: cloudflared
  tls:
    - hosts:
        - events.7tv.app
      secretName: 7tv-app-tls
  rules:
    - host: events.7tv.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eventapi
                port:
                  name: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eventapi
  namespace: monitoring
  labels:
    app: eventapi
    release: prometheus
spec:
  jobLabel: eventapi
  selector:
    matchLabels:
      app: eventapi
  namespaceSelector:
    matchNames:
      - app
  endpoints:
    - port: metrics
